/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author Acer
 */
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class EDITITEM extends javax.swing.JFrame {

    private MANAGEINVENTORY manageInventoryFrame;
    private JSONObject currentItem;

    public EDITITEM(MANAGEINVENTORY manageInventoryFrame, String itemNumber, String name, int quantity, double price) {
        initComponents();
        this.manageInventoryFrame = manageInventoryFrame;

        ItemNumLabel.setText(itemNumber); // Show itemNumber in label
        NameF.setText(name);
        StocksF.setText(String.valueOf(quantity));
        PriceF.setText(String.valueOf(price));

        currentItem = new JSONObject();
        currentItem.put("itemNumber", itemNumber); // Changed 'itemId' to 'itemNumber'
        currentItem.put("name", name);
        currentItem.put("quantity", quantity);
        currentItem.put("price", price);
    }

    public EDITITEM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameF = new javax.swing.JTextField();
        PriceF = new javax.swing.JTextField();
        CancelBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        StocksF = new javax.swing.JTextField();
        SaveChangesBtn = new javax.swing.JButton();
        ItemNumLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BGFINAL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(NameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 204, 264, 32));
        getContentPane().add(PriceF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 304, 264, 32));

        CancelBtn.setBackground(new java.awt.Color(217, 234, 253));
        CancelBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        CancelBtn.setText("CANCEL");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 454, 170, 42));

        DeleteBtn.setBackground(new java.awt.Color(217, 234, 253));
        DeleteBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(204, 0, 51));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 396, 170, 42));
        getContentPane().add(StocksF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 254, 264, 32));

        SaveChangesBtn.setBackground(new java.awt.Color(217, 234, 253));
        SaveChangesBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SaveChangesBtn.setForeground(new java.awt.Color(0, 0, 0));
        SaveChangesBtn.setText("SAVE CHANGES");
        SaveChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveChangesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 396, 170, 42));

        ItemNumLabel.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        ItemNumLabel.setForeground(new java.awt.Color(0, 0, 0));
        ItemNumLabel.setText("ItemNumberLabel");
        getContentPane().add(ItemNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 160, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Item No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 74, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Item Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 208, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("STOCKHUB");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Quantity:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 257, 74, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EDIT ITEM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 93, 74, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Order and Inventory System");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Price:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 308, 50, -1));

        BGFINAL.setForeground(new java.awt.Color(0, 0, 0));
        BGFINAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/EDIT ITEM BG FINAL.png"))); // NOI18N
        BGFINAL.setText("jLabel6");
        getContentPane().add(BGFINAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 529));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        deleteItem();
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void SaveChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesBtnActionPerformed
        // TODO add your handling code here:
        saveChanges();
    }//GEN-LAST:event_SaveChangesBtnActionPerformed
   private void saveChanges() {
        try {
            String newItemNumber = ItemNumLabel.getText().trim();
            String newName = NameF.getText().trim();
            String quant = StocksF.getText().trim();
            String priceStr = PriceF.getText().trim();

            if (newName.isEmpty() || quant.isEmpty() || priceStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Please fill in all the fields.",
                        "Missing Info",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int newQuantity;
            double newPrice;
            try {
                newQuantity = Integer.parseInt(quant);
                newPrice = Double.parseDouble(priceStr);

                if (newQuantity < 0 || newPrice < 0.0) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Quantity and price must not be below 0.",
                            "Invalid Input",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Quantity and price must be valid numbers.",
                        "Invalid Input",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            JSONParser parser = new JSONParser();
            JSONArray items = (JSONArray) parser.parse(new FileReader("src//Main//Items.json"));

            String originalItemNumber = (String) currentItem.get("itemNumber");
            String originalName = (String) currentItem.get("name");

            boolean nameExists = false;
            boolean numberExists = false;

            for (Object o : items) {
                JSONObject item = (JSONObject) o;
                String existingItemNumber = (String) item.get("itemNumber");
                String existingName = (String) item.get("name");

                if (!existingItemNumber.equals(originalItemNumber) && existingItemNumber.equals(newItemNumber)) {
                    numberExists = true;
                    break;
                }

                if (!existingName.equals(originalName) && existingName.equalsIgnoreCase(newName)) {
                    nameExists = true;
                }
            }

            if (numberExists) {
                JOptionPane.showMessageDialog(
                        this,
                        "Item number already exists.",
                        "Duplicate Number",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            if (nameExists) {
                JOptionPane.showMessageDialog(
                        this,
                        "Item name already exists.",
                        "Duplicate Name",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to save changes?",
                    "Confirm Save",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            for (int i = 0; i < items.size(); i++) {
                JSONObject item = (JSONObject) items.get(i);
                if (item.get("itemNumber").equals(originalItemNumber)) {
                    item.put("itemNumber", newItemNumber);
                    item.put("name", newName);
                    item.put("quantity", newQuantity);
                    item.put("price", newPrice);
                    break;
                }
            }

            try (FileWriter file = new FileWriter("src//Main//Items.json")) {
                file.write(items.toJSONString());
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Changes saved successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );

            setVisible(false);
            if (manageInventoryFrame != null) {
                manageInventoryFrame.loadItems();
            }
            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Quantity and price must be valid numbers.",
                    "Invalid Input",
                    JOptionPane.WARNING_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Something went wrong while saving changes.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

    private void deleteItem() {
        try {
            String itemNumberToDelete = ItemNumLabel.getText().trim();

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this item?",
                    "Confirm Delete",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            JSONParser parser = new JSONParser();
            JSONArray items = (JSONArray) parser.parse(new FileReader("src//Main//Items.json"));

            boolean itemFound = false;

            for (int i = 0; i < items.size(); i++) {
                JSONObject item = (JSONObject) items.get(i);
                if (item.get("itemNumber").equals(itemNumberToDelete)) {
                    items.remove(i);
                    itemFound = true;
                    break;
                }
            }

            if (!itemFound) {
                JOptionPane.showMessageDialog(this, "Item not found.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            try (FileWriter file = new FileWriter("src//Main//Items.json")) {
                file.write(items.toJSONString());
            }

            JOptionPane.showMessageDialog(this, "Item deleted successfully.", "Deleted", JOptionPane.INFORMATION_MESSAGE);
            manageInventoryFrame.loadItems();
            dispose();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Something went wrong while deleting.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDITITEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDITITEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDITITEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDITITEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDITITEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGFINAL;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel ItemNumLabel;
    private javax.swing.JTextField NameF;
    private javax.swing.JTextField PriceF;
    private javax.swing.JButton SaveChangesBtn;
    private javax.swing.JTextField StocksF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
