/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author Acer
 */

import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class LOGIN extends javax.swing.JFrame {

    private static String usname, pass;
    private static String filepath = "src\\Main\\employee.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray userlist = new JSONArray();

    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Password = new javax.swing.JLabel();
        UserF = new javax.swing.JTextField();
        PassF = new javax.swing.JPasswordField();
        Usr = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setText("Password:");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 300, 100, -1));

        UserF.setMinimumSize(new java.awt.Dimension(68, 27));
        UserF.setPreferredSize(new java.awt.Dimension(69, 28));
        getContentPane().add(UserF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 310, 32));
        getContentPane().add(PassF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 325, 310, 32));

        Usr.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        Usr.setForeground(new java.awt.Color(0, 0, 0));
        Usr.setText("Username:");
        getContentPane().add(Usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 205, 90, -1));

        LoginBtn.setBackground(new java.awt.Color(38, 67, 114));
        LoginBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("LOGIN");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 130, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order and Inventory System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STOCKHUB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 100, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Login Page (2).png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 969, 608));

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Order and Inventory System");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String username = UserF.getText().trim();
        String password = PassF.getText().trim();

        if (username.isEmpty() && password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter your username and password to continue.", "Login", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your username.", "Login", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your password.", "Login", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            usname = username;
            pass = password;

            filecheck();

            boolean usernameExists = false;
            boolean userFound = false;
            String foundRole = null;

            for (Object obj : userlist) {
                JSONObject userobject = (JSONObject) obj;
                String foundusname = (String) userobject.get("username");
                String foundpass = (String) userobject.get("password");

                if (usname.equals(foundusname)) {
                    usernameExists = true;

                    if (pass.equals(foundpass)) {
                        userFound = true;
                        foundRole = (String) userobject.get("role");
                    }

                    break;
                }
            }

            if (!usernameExists) {
                JOptionPane.showMessageDialog(this, "No username found.", "Try again", JOptionPane.ERROR_MESSAGE);
            } else if (!userFound) {
                JOptionPane.showMessageDialog(this, "The password you entered is incorrect.", "Try again", JOptionPane.ERROR_MESSAGE);
            } else {
                if (foundRole.equalsIgnoreCase("Admin")) {
                    new ADMINMENU().setVisible(true);
                } else if (foundRole.equalsIgnoreCase("Employee")) {
                    new EMPLOYEEMENU().setVisible(true);
                }
                this.dispose();
            }

        } catch (HeadlessException | IOException | ParseException e) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Something went wrong. Please try again later.", "Oops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    public static String getusname() {
        return usname;
    }

    public static void filecheck() throws FileNotFoundException, IOException, ParseException {
        FileReader reader = new FileReader(filepath);

        if (reader.ready()) {
            Scanner scan = new Scanner(reader);
            String line = "";

            while (scan.hasNext()) {
                line = line + scan.nextLine();
            }

            if (!line.equals("")) {
                reader.close();
                FileReader reader2 = new FileReader(filepath);
                record = (JSONObject) jsonParser.parse(reader2);
                userlist = (JSONArray) record.get("employee");
                reader2.close();
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPasswordField PassF;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField UserF;
    private javax.swing.JLabel Usr;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
