/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author Acer
 */
import java.awt.Color;
import java.awt.Font;
import java.io.FileReader;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class MANAGEINVENTORY extends javax.swing.JFrame {

    public MANAGEINVENTORY() {
        initComponents();
        loadItems();
        SearchF.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                loadItems();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                loadItems();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                loadItems();
            }
        });
        ItemTable.getTableHeader().setFont(new Font("Segoe UI Variable", Font.PLAIN, 14));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        JTable[] tables = {ItemTable};

        for (JTable table : tables) {
            // Center cells
            for (int i = 0; i < table.getColumnCount(); i++) {
                table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

            // Custom header renderer with background color and bold font
            JTableHeader header = table.getTableHeader();
            DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
            headerRenderer.setHorizontalAlignment(JLabel.CENTER);
            headerRenderer.setBackground(Color.decode("#325ea0")); // Your desired color
            headerRenderer.setForeground(Color.WHITE); // White text looks good on dark blue

            // Set font to Segoe UI, size 14, and bold for header only
            headerRenderer.setFont(new Font("Segoe UI", Font.BOLD, 14));  // Ensure it's bold

            // Apply the custom header renderer to each column
            for (int i = 0; i < table.getColumnCount(); i++) {
                table.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            }

            // Repaint to apply the changes
            header.repaint();  // Ensure the header is repainted after changes
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddItemBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        StockLevelComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SearchF = new javax.swing.JTextField();
        EditBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        BGFINAL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddItemBtn.setBackground(new java.awt.Color(217, 234, 253));
        AddItemBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        AddItemBtn.setForeground(new java.awt.Color(0, 0, 0));
        AddItemBtn.setText("ADD NEW ITEM");
        AddItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddItemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 170, 42));

        BackBtn.setBackground(new java.awt.Color(217, 234, 253));
        BackBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 0, 0));
        BackBtn.setText("BACK");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, 170, 42));

        StockLevelComboBox.setBackground(new java.awt.Color(217, 234, 253));
        StockLevelComboBox.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        StockLevelComboBox.setForeground(new java.awt.Color(0, 0, 0));
        StockLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Level", "Normal Stock", "Low Stock", "Overstock" }));
        StockLevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockLevelComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(StockLevelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 184, 140, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Item:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 145, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filter:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 39, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STOCKHUB");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Order and Inventory System");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 40, -1, -1));
        getContentPane().add(SearchF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 345, 32));

        EditBtn.setBackground(new java.awt.Color(217, 234, 253));
        EditBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(0, 0, 0));
        EditBtn.setText("EDIT ITEM");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 170, 42));

        ItemTable.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item No.", "Item Name", "Price per item", "Stocks", "Stock Level"
            }
        ));
        ItemTable.setIntercellSpacing(new java.awt.Dimension(0, 5));
        ItemTable.setRowHeight(25);
        jScrollPane2.setViewportView(ItemTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 240, 906, 243));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGE INVENTORY");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 92, 150, -1));

        BGFINAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/MANAGEINVENTORY BG FINAL.png"))); // NOI18N
        BGFINAL.setText("jLabel1");
        getContentPane().add(BGFINAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StockLevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockLevelComboBoxActionPerformed
        // TODO add your handling code here:
        loadItems();
    }//GEN-LAST:event_StockLevelComboBoxActionPerformed

    private void AddItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemBtnActionPerformed
        // TODO add your handling code here:
        ADDITEM x = new ADDITEM(this); // Pass current MANAGEINVENTORY instance
        x.setVisible(true);
    }//GEN-LAST:event_AddItemBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        ADMINMENU x = new ADMINMENU();
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        editSelectedItem();

    }//GEN-LAST:event_EditBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void loadItems() {
         DefaultTableModel model = (DefaultTableModel) ItemTable.getModel();
        model.setRowCount(0);
        String keyword = SearchF.getText().toLowerCase();
        String selectedFilter = StockLevelComboBox.getSelectedItem().toString();
        ItemTable.getTableHeader().setFont(new Font("Segoe UI Variable", Font.PLAIN, 14));

        try {
            JSONParser parser = new JSONParser();
            JSONArray itemsArray = (JSONArray) parser.parse(new FileReader("src//Main//Items.json"));

            itemsArray.sort((o1, o2) -> {
                JSONObject item1 = (JSONObject) o1;
                JSONObject item2 = (JSONObject) o2;
                String id1 = item1.get("itemNumber").toString();
                String id2 = item2.get("itemNumber").toString();
                return id1.compareTo(id2);
            });

            for (Object obj : itemsArray) {
                JSONObject item = (JSONObject) obj;
                String itemNumber = item.get("itemNumber").toString();
                String name = item.get("name").toString();
                long quantity = (long) item.get("quantity");
                double price = (double) item.get("price");

                String stockLevel = getStockLevel(quantity);
                String formattedPrice = "₱" + String.format("%.2f", price);

                boolean matchesSearch = name.toLowerCase().contains(keyword) || itemNumber.toLowerCase().contains(keyword);
                boolean matchesFilter = selectedFilter.equals("All Level") || selectedFilter.equals(stockLevel);

                if (matchesSearch && matchesFilter) {
                    model.addRow(new Object[]{itemNumber, name, formattedPrice, quantity, stockLevel});
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String getStockLevel(long quantity) {
        if (quantity <= 10) {
            return "Low Stock";
        } else if (quantity <= 100) {
            return "Normal Stock";
        } else {
            return "Overstock";
        }
    }

    private void editSelectedItem() {
        int selectedRow = ItemTable.getSelectedRow();
        if (selectedRow != -1) {
            String itemNumber = ItemTable.getValueAt(selectedRow, 0).toString();
            String name = ItemTable.getValueAt(selectedRow, 1).toString();
            String priceStr = ItemTable.getValueAt(selectedRow, 2).toString().replace("₱", "").trim();
            String quantityStr = ItemTable.getValueAt(selectedRow, 3).toString();

            try {
                double price = Double.parseDouble(priceStr);
                int quantity = Integer.parseInt(quantityStr);

                EDITITEM editItemFrame = new EDITITEM(this, itemNumber, name, quantity, price);
                editItemFrame.setVisible(true);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Failed to parse item details.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item to edit.", "No Selection", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGEINVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGEINVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGEINVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGEINVENTORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGEINVENTORY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemBtn;
    private javax.swing.JLabel BGFINAL;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTable ItemTable;
    private javax.swing.JTextField SearchF;
    private javax.swing.JComboBox<String> StockLevelComboBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
